# Generated by Django 5.2.6 on 2025-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
